In [1]:
import numpy as np
import pandas as pd

### Import toy regression data

In [2]:
X = pd.read_csv('data/toy-regression-features.csv')
y = pd.read_csv('data/toy-regression-labels.csv')

In [3]:
X.head()

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_290,col_291,col_292,col_293,col_294,col_295,col_296,col_297,col_298,col_299
0,0.537070,-1.102140,1.614065,0.446704,2.150072,0.022795,-0.062325,0.842601,1.337646,0.423004,...,-0.923334,-0.481815,1.203645,-1.458585,-0.382055,0.778446,1.281670,0.083526,0.690047,0.117204
1,-0.291104,0.870662,0.989858,0.340181,0.462467,-0.582148,1.888760,1.326881,-1.654321,-0.130696,...,1.429273,0.845691,-1.089257,-0.918355,0.394018,2.608926,-1.485463,-0.907812,-0.173660,0.920506
2,-0.623914,0.645679,-0.603598,-0.382241,-1.038855,1.036846,-0.411746,0.309138,0.377860,1.115033,...,-0.853996,-1.977211,-0.360070,0.457125,-1.372804,0.320784,-0.961563,-0.203412,0.920264,0.799161
3,-0.007280,-1.159284,1.205723,-0.869215,-0.571466,0.540196,0.656639,0.041661,0.244310,-0.860549,...,0.646255,-0.762227,-0.940969,-0.889827,-0.534136,-0.649951,-0.387092,-1.089814,0.054935,0.955872
4,0.578238,-0.756635,-0.768636,1.339886,0.612525,-0.431343,-0.058266,0.975151,-1.992118,0.179272,...,0.263658,0.837735,0.724682,-2.493489,-2.108600,-1.646070,-0.674911,-0.344457,-0.771689,-0.691474

In [4]:
y.head()

       labels
0  219.664211
1   40.998126
2  109.423858
3 -280.667507
4  599.178538

### Use the library to select only the relevant features

In [5]:
from src.ml import get_relevant_features, scan_features
from sklearn.linear_model import Lasso

lasso_model = Lasso(alpha=1)

X_reduced = get_relevant_features(X, y, 
                                  model=lasso_model, 
                                  epochs=100, 
                                  patience=5, 
                                  filename_output='results/reduced_dataset.csv')

=====================EPOCH 1 =====================
Fitting the model with 301 features
Train score 0.9344
Test score 0.8207
Selected 202 features out of 300
=====================EPOCH 2 =====================
Fitting the model with 203 features
Train score 0.9227
Test score 0.8614
Selected 148 features out of 202
=====================EPOCH 3 =====================
Fitting the model with 149 features
Train score 0.9163
Test score 0.8963
Selected 148 features out of 148
The feature selection did not improve in the last 1 epochs
=====================EPOCH 4 =====================
Fitting the model with 149 features
Train score 0.9199
Test score 0.8668
Selected 41 features out of 148
=====================EPOCH 5 =====================
Fitting the model with 42 features
Train score 0.9056
Test score 0.8772
Selected 28 features out of 41
=====================EPOCH 6 =====================
Fitting the model with 29 features
Train score 0.895
Test score 0.9077
Selected 26 features out of 28
=====================EPOCH 7 =====================
Fitting the model with 27 features
Train score 0.8997
Test score 0.8878
Selected 26 features out of 26
The feature selection did not improve in the last 1 epochs
=====================EPOCH 8 =====================
Fitting the model with 27 features
Train score 0.9024
Test score 0.8805
Selected 26 features out of 26
The feature selection did not improve in the last 2 epochs
=====================EPOCH 9 =====================
Fitting the model with 27 features
Train score 0.9024
Test score 0.8809
Selected 26 features out of 26
The feature selection did not improve in the last 3 epochs
=====================EPOCH 10 =====================
Fitting the model with 27 features
Train score 0.8977
Test score 0.8977
Selected 26 features out of 26
The feature selection did not improve in the last 4 epochs
=====================EPOCH 11 =====================
Fitting the model with 27 features
Train score 0.8973
Test score 0.9005
Selected 26 features out of 26
The feature selection did not improve in the last 5 epochs

###Â Inspect the new (reduced) dataset

In [6]:
X_reduced.head()

,col_88,col_168,col_277,col_283,col_270,col_8,col_258,col_187,col_171,col_76,...,col_174,col_250,col_24,col_25,col_45,col_55,col_274,col_263,col_90,col_154
0,-1.019952,-0.003067,-0.003618,-2.092326,0.220574,1.337646,1.673497,0.236082,-0.878309,0.656732,...,0.577020,1.053236,-0.309741,1.178854,1.498433,0.800531,0.692207,0.530798,-1.202006,-1.750620
1,0.920548,0.030676,0.259951,0.685426,-0.041250,-1.654321,-0.051170,0.853362,-0.343505,-0.367285,...,0.653817,-1.545429,0.830601,-0.570561,-1.335906,-0.017992,-0.808267,0.390875,0.392990,-1.292565
2,-3.277806,0.459295,-1.351804,0.933398,0.758731,0.377860,0.971993,-0.739010,-0.076279,0.200066,...,-0.260010,2.176639,-1.145208,1.957113,-0.852144,0.742541,-1.399284,-0.646471,-0.202683,1.935704
3,-0.936796,0.002783,-0.413398,1.153329,-0.781265,0.244310,0.744198,1.123666,-0.379941,0.328173,...,-0.077514,-2.033497,-1.016165,0.245085,0.389595,-0.630077,0.221333,0.874562,2.128844,0.210160
4,0.842412,0.054107,3.081069,-0.148948,0.513912,-1.992118,0.093666,2.831712,0.741283,1.261611,...,-0.676896,0.351711,2.785978,-0.719393,-0.178059,-1.068996,0.234328,0.846569,-1.531923,-0.086358